name: random-coffee-app

services:
  bot-service:
    container_name: bot-service
    tty: true
    env_file: ./.env
    image: mituta/bot-service:latest
    platform: linux/x86_64
  api-gateway:
    container_name: api-gateway
    tty: true
    env_file: ./.env
    image: mituta/api-gateway:latest
    platform: linux/x86_64
    ports:
      - "8080:8080"
  profile-service:
    container_name: profile-service
    tty: true
    image: mituta/profile-service:latest
    platform: linux/x86_64
    env_file: ./.env
    ports:
      - "8081:8081"
  profile-db:
    container_name: profile-db
    tty: true
    image: postgres:latest
    platform: linux/x86_64
    env_file: ./.env
    environment:
      - POSTGRES_DB=profile-db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - profile-db-volume:/var/lib/postgresql/data
  mini-app:
    container_name: mini-app
    tty: true
    env_file: ./.env
    image: mituta/mini-app:latest
    ports:
      - "3000:3000"
    platform: linux/x86_64
  ml:
    container_name: ml
    tty: true
    env_file: ./.env
    image: mituta/ml:latest
    platform: linux/x86_64
    ports:
      - "8000:8000"