spring:
  application:
    name: "API-gateway"
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOriginPatterns: "*"
                allowedMethods: "*"
                allowedHeaders: "*"
                allowCredentials: false
                maxAge: 3600
                exposedHeaders:
                  - "Content-Length"
                  - "Authorization"
            add-to-simple-url-handler-mapping: true
profile-service:
  url: "http://${PROFILE_SERVICE_HOST:profile-service}:8081"
mini-app:
  authorization:
    header-name: "Authorization"