name: CI

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start containers
        run: |
          docker compose -f compose-dev.yaml up -d --build

      - name: Wait for containers to be up and running
        run: |
          echo "Waiting for containers to start..."
          sleep 30

          if ! docker ps | grep -q "mini-app"; then
            echo "Error: mini-app container is not running"
            exit 1
          fi

          if ! docker port mini-app | grep -q ":"; then
            echo "Error: No ports are exposed on mini-app container"
            exit 1
          fi

          # Check all containers status
          if docker compose -f compose-dev.yaml ps -a | grep -q "Exited ([1-9][0-9]*\|[2-9])"; then
            echo "Error: Some containers exited with non-zero status"
            docker compose -f compose-dev.yaml ps -a
            exit 1
          fi

          echo "Frontend container is running and has exposed ports"
          docker compose -f compose-dev.yaml ps -a

      - name: Show container logs
        run: |
          echo "=== Bot Service Logs ==="
          docker logs bot-service

          echo "=== API Gateway Logs ==="
          docker logs api-gateway

          echo "=== Mini App Logs ==="
          docker logs mini-app

          echo "=== ML Service Logs ==="
          docker logs ml
